#!/bin/sh -e

oname=tidyr
pkg=r-cran-`echo $oname | tr [A-Z] [a-z]`

if [ "$AUTOPKGTEST_TMP" = "" ] ; then
  AUTOPKGTEST_TMP=`mktemp -d /tmp/${pkg}-test.XXXXXX`
fi
cd $AUTOPKGTEST_TMP
cp -a /usr/share/doc/${pkg}/tests/* $AUTOPKGTEST_TMP
LC_ALL=C R --no-save < testthat.R
rm -fr $AUTOPKGTEST_TMP/*
